version: "3.7"
services:
  myapplication:
    build: .
    ports:
      - "5000:5000"
    links:
      - localdb
      - jupyter
  localdb:
    image: "mysql:latest"
    environment:
      - MYSQL_USER=myapplicationuser
      - MYSQL_PASSWORD=abc123!@#
      - MYSQL_DATABASE=myapplication
      - MYSQL_ROOT_PASSWORD=password123
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
  jupyter:
    image: "jupyter/base-notebook:latest"
    ports:
      - '8888:8888'
    expose:
      - '8888'
    volumes:
      - ./jupyter-data:/home/jovyan/work
